### PR TITLE
Added more feedback options.

### PR DESCRIPTION
**Pull request by 0-Blu**
### Changes

- Added more feedback options.
image

### CODE REVIEW

**Review by polymo1 — APPROVED** [review]
visually lgtm, wait for code review

**Comment by polymo1** [comment]
well, suggestion: change mail to "Send email to <whatever the email address is>" in case they use a different email client or wanna send it themselves. but thats just me

**Review by SternXD — APPROVED** [review]
This lgtm.

**Comment by 0-Blu** [comment]
I changed Mail to Send Email

**Comment by Spidy123222** [comment]
We currently don't accept email, we could in future however.

**Comment by 0-Blu** [comment]
@Spidy123222 I know you said you don’t accept email but that is what happens when you hit send feedback currently.

**Comment by SternXD** [comment]
> @Spidy123222 I know you said you don’t accept email but that is what happens when you hit send feedback currently.

Something at the moment you can do is comment it out and when we need it we can uncomment it out.

**Comment by SternXD** [comment]
Alright seems good l approve of this being merged

**Pull request merged**
