### PR TITLE
Release channel support

### PR DESCRIPTION
**Pull request by amsam0**
#239

before merge, we should change sidestore-apps.naturecodevoid.dev to apps.sidestore.io (we will need to deploy the worker to apps.sidestore.io first)

### CODE REVIEW

**Comment by naturecodevoid** [comment]
This PR will be broken until we setup apps.sidestore.io, use [this build](https://github.com/SideStore/SideStore/pull/239#issuecomment-1413966588) to use the old URL

**Comment by Spidy123222** [comment]
> This PR will be broken until we setup apps.sidestore.io, use [this build](https://github.com/SideStore/SideStore/pull/239#issuecomment-1413966588) to use the old URL

Is that all you need to do now if so we could start the process soon.

**Comment by naturecodevoid** [comment]
I'd like to finish the actions improvements first, then we can move users to a beta

**Comment by Spidy123222** [comment]
I think since we are going to use SideStore connect, might be best to do what that supports and just do our own source system for connect. For now I'll close this PR

**Pull request closed without merging**
