### PR TITLE
Emotional Damage!

### PR DESCRIPTION
**Pull request by jkcoxson**
Initial implementation of emotional damage!

## What works
- [x] I have emotional damage
- [x] Enabling JIT
- [x] Yeeting apps with AFC
- [x] Installing yeeted apps
- [x] Heartbeat
- [x] GitHub builds
- [x] Enabling apps
- [x] Disabling apps
- [x] Refreshing apps
- [x] Managing installed profiles
- [x] Mounting developer disk images

### CODE REVIEW

**Comment by jkcoxson** [comment]
Refreshing needs a sanity check

**Comment by jkcoxson** [comment]
According to @jawshoeadan activating and deactivating works. I'm guessing it's because I did all my testing from Xcode installs.

**Comment by jkcoxson** [comment]
My PR is ready for review, let's make sure everything is working as intended.

**Comment by jkcoxson** [comment]
Okay just because we need to get the project moving and others can rebase, I'll give everyone 24 hours to object on why this shouldn't be merged. After that, I'm pressing the big green button. Not a threat, just a promise.

**Review by jawshoeadan — APPROVED** [review]
lgtm!

**Comment by JoeMatt** [comment]
I’ll look at it in a bit. I’m up all night

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by Nythepegasus — APPROVED** [review]
I think everything here is ready to go, we can always fix things later 🤞

**Comment by JoeMatt** [comment]
I got this to build and run. 

Issues installing apps but that seems to be anisette or something

**Review by JoeMatt — APPROVED** [review]

**Comment by jkcoxson** [comment]
yeet

**Pull request merged**
