### PR TITLE
[WIP] Fix duplicate profiles

### LINKED ISSUE #249: [BUG] Duplicate provisioning profiles causes SideStore to expire randomly
**Describe the bug**
Refreshed all apps at once, including SideStore, but SideStore seems to expire earlier  (`SideStore No Longer Available`) than all other apps. Other apps launched just fine. Reproducible with every latest build in Actions.

**To Reproduce**
1. Refresh all apps
2. Wait few days (4-5 days if not mistaken)
3. SideStore expire

**Expected behavior**
Expire on time, rather than early.

**iDevice (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 16.1.2-16.3

### PR DESCRIPTION
**Pull request by naturecodevoid**
### Changes

- Fix duplicate provisioning profiles by removing all profiles associated with an app before installing/refreshing

### Todo before merge

- [x] Merge both minimuxer PRs and update submodule
- [ ] Fix instant expire
- [ ] Fix expire after a few hours

Closes #249

### CODE REVIEW

**Comment by velaar** [comment]
I wonder is a certain combination of profile_cleaner.py and this build can actually work. I think the build (in expire instantly scenario) is removing the profile that it just was signed with instead of the one that it was installed with previously.

**Comment by naturecodevoid** [comment]
It doesn’t. I added logs that show what profile is being used to sign. It uses the new profile. I don’t know why it doesn’t work. Team members with more experience with this than me will have to investigate

**Comment by velaar** [comment]
Sorry for a newbie question. How can I access these logs? Especially after it’s unsigned. On Feb 25, 2023, at 12:39 PM, naturecodevoid ***@***.***> wrote:﻿
It doesn’t. I added logs that show what profile is being used to sign. It uses the new profile. I don’t know why it doesn’t work. Team members with more experience with this than me will have to investigate

**Comment by naturecodevoid** [comment]
Here’s what you should look for: https://github.com/SideStore/SideStore/pull/262/files#diff-5be1bd4140171972039e999eecf514a02281d38e1dd7cb6a5da648cc61d8f383R246
You will need to run `idevicedebug run com.SideStore.SideStore.[your team ID]`. Currently, we don’t save logs to disk, but the SwiftUI branch will have a button to export logs as a .txt file.
You can check if it’s using the right profile by comparing the profile UUIDs outputted by `ideviceprovision list` to the ones logged when resigning.

(you will need libimobiledevice installed)

**Comment by velaar** [comment]
So here is a log that I've got. Immediately after that the Side Store is no longer available. Does it mean that somehow the app I have is still signed by the AltStore ? Is there a way to check that? Sorry for too many question. Just trying to help.

```
18:19:05 [INFO] Logger initialized!!
18:19:05 [INFO] Starting heartbeat thread
18:19:08 [INFO] Heartbeat success!
18:19:11 [INFO] Developer disk image already mounted
18:19:11 [INFO] Auto image mounter has finished, have a great day!
18:19:19 [INFO] Heartbeat success!
18:19:29 [INFO] Heartbeat success!
18:19:40 [INFO] Heartbeat success!
18:19:43 [INFO] Removing iOS Team Provisioning Profile: com.SideStore.SideStore.D7DTX9524Z (a7cf5701-6fbc-41e7-9dd6-8c9c2a19089c) since it contained an ID we received
18:19:43 [INFO] Success!
18:19:43 [INFO] Removing iOS Team Provisioning Profile: com.SideStore.SideStore.D7DTX9524Z.AltWidget (8f810022-e99c-4de4-8be9-cd5f645edad3) since it contained an ID we received
18:19:43 [INFO] Success!
18:19:43 [INFO] Finished removing inactive profiles
18:19:43 [INFO] Minimuxer finished installing profile!!
18:19:43 [INFO] Minimuxer finished installing profile!!
18:19:51 [INFO] Heartbeat success!
18:20:01 [INFO] Heartbeat success!
18:20:12 [INFO] Heartbeat success!
```

**Comment by naturecodevoid** [comment]
Thank you for trying to help. It seems like SideStore is being resigned correctly with the new profiles (not 100% sure since minimuxer logs don't include app logs yet), but as you said, it is still unavailable. I don't know why this happens. Many team members have been investigating the entire duplicate provisioning profiles issue over the past few days. They are trying to figure out what the cause is when it happens on nightly, and no one has investigated this PR not working yet. This PR will likely never be merged, as there is a good chance we will find the root cause before the issues with this PR are fixed.

**Pull request closed without merging**
