### PR TITLE
Build Rust depends in XCode

### PR DESCRIPTION
**Pull request by JoeMatt**
Added external `cargo` build phases to XCode proj.

Expects `cargo` to be in `~/.cargo/bin/cargo`

### CODE REVIEW

**Comment by JoeMatt** [comment]
Looks like I need to do something different for github actions. 

Probably `which cargo` first result rather than hard coded path

**Comment by JoeMatt** [comment]
Added a wrapper script for cargo to fix xcode being xcode. Should fix CI...

**Comment by f1shy-dev** [comment]
Possible we could also check for the simulator and accordingly build the x86_64-apple-ios libraries?

Would be helpful for UI testing and etc ig

**Comment by JoeMatt** [comment]
I found a cargo plugin that autogenerates xcode projects files from a cargo .toml.

I simplified this PR by creating those files in the project deps dir along with a script to re-gen if needed.

https://crates.io/crates/cargo-xcode

**Pull request merged**
