### PR TITLE
Update InstalledApp.swift

### PR DESCRIPTION
**Pull request by taicracker**
### Changes

- Fix bug
- Change UI for QOL

### Todo before merge

- [x] Finish UI changes
- [ ] Test

Closes #1234

### CODE REVIEW

**Review by silxl — COMMENTED** [review]
AltStoreCore/Model/InstalledApp.swift

**Review by silxl — COMMENTED** [review]
gh pr checkout 354

**Comment by silxl** [comment]
https://github.com/SideStore/SideStore/compare/0.1.1...0.3.1

**Comment by Nythepegasus** [comment]
Hello! Can you do testing on your own repos? Thank you!

**Pull request closed without merging**
