### PR TITLE
add pokemmo into trusted sources.

### PR DESCRIPTION
**Pull request by Spidy123222**
This adds pokemmo in the list of trusted sources.

### CODE REVIEW

**Comment by jawshoeadan** [comment]
Looks great! I don't see any reason not to merge.

**Comment by Spidy123222** [comment]
Nice well I'm trying to essentially get any sources we trust and put it in there and it was on community store and we don't really need it parse a source unless it's needed to support newer altsource.

**Comment by upal212** [comment]
@Spidy123222 PokeMMO seems to be only showing up while tapping on the search dialogue else it shows empty. Is that an usual behaviour?

**Comment by Spidy123222** [comment]
> @Spidy123222 PokeMMO seems to be only showing up while tapping on the search dialogue else it shows empty. Is that an usual behaviour?

I didn’t find this during testing but I do now get this behavior. Not quite sure if it’s sidestore or their source. The source they have for the formatting of the json doesn’t look out of ordinary so it’s likely sidestore problem. Maybe a test with AltStore to confirm that could help. They do have the beta label on and could be hiding from us.

**Comment by upal212** [comment]
> 

Maybe it could be the sources of the AltStore beta acting abnormally. Comparing the changes with the latest could help with this.

**Pull request merged**
