### PR TITLE
[WIP] Test WireGuard extension

### PR DESCRIPTION
**Pull request by JoeMatt**
This builds an empty NetworkExtension following these instructions.

https://github.com/WireGuard/wireguard-apple#wireguardkit-integration

A purely academic exercise at the moment. I spent some time getting it to build correctly so storing here for more tinquring later.

### CODE REVIEW

**Comment by lonkelle** [comment]
@JoeMatt Would this be for a future "auto-VPN" for Paid Apple Developers that can sign using the Networking Entitlement (foregoing the need for the Wireguard app)?

**Comment by JoeMatt** [comment]
closing for now, nothing really in here anyway

**Comment by lonkelle** [comment]
@JoeMatt What was the point exactly of this PR? Was it what I mentioned in my last comment?

**Comment by JJTech0130** [comment]
If we are intending to support paid developer accounts, it's much easier to forgo WireGuard altogether and just use Jitterbug's loopback VPN

**Comment by lonkelle** [comment]
@JJTech0130 Good point, that's what we'll do. But osy did say their loopback VPN quirk is "impossibly easy to patch". So we'll reopen this if they ever patch that since osy said that years ago and they still haven't patched it..

**Pull request closed without merging**
