### PR TITLE
Add various retries throughout the Rust function calls

### PR DESCRIPTION
**Pull request by Nythepegasus**
I currently have this set to retry 10 times per function. We could probably move the retry amount to a const, or some form of setting for the user, but I thought 10 was decent as a default for now.

### CODE REVIEW

**Comment by Spidy123222** [comment]
Works well but with jit enabling it has a chance of spamming debugger which opens app 10 times.

**Comment by lonkelle** [comment]
@Spidy123222 Good catch, so we have to make an exception for the "OPEN APP" part of the JIT flow.

**Comment by Spidy123222** [comment]
> @Spidy123222 Good catch, so we have to make an exception for the "OPEN APP" part of the JIT flow. 

Debugging the app auto opens. So need a way to detect if the app got debugged or if the debug succeeded.

**Comment by lonkelle** [comment]
Looks like the only thing barring this from being merged is the JIT-opening bug. So I put it as a milestone for our soft launch.

**Review by JoeMatt — APPROVED** [review]
good, but note to self, after merge, replace print's with the logging functions from riley's branch when it's all done

**Pull request merged**
