### PR TITLE
Fix beta apps on the my apps view, and fix deactivating/activating apps

### PR DESCRIPTION
**Pull request by jawshoeadan**

### CODE REVIEW

**Comment by upal212** [comment]
Loading of ‘Trusted Sources’ list is failing.

**Comment by upal212** [comment]
Working as intended and seems to fix the staging issues as well during the IPA installations.

**Review by Nythepegasus — APPROVED** [review]

**Comment by upal212** [comment]
‘Refresh All’ button doesn’t seem to refresh the apps with the ‘Beta’ badge on it.

**Review by upal212 — CHANGES_REQUESTED** [review]
‘Refresh All’ button doesn’t seem to refresh the apps with the ‘Beta’ badge on it.

**Comment by jawshoeadan** [comment]
> ‘Refresh All’ button doesn’t seem to refresh the apps with the ‘Beta’ badge on it.

This should be fixed now, try out the new ipa from this actions run and lmk if it fixed it!

**Comment by Spidy123222** [comment]
Deactivating seems to crash sidestore. https://user-images.githubusercontent.com/64176728/206938793-05e27884-66e6-4e26-a489-b40036a44400.MOV

**Comment by upal212** [comment]
> Deactivating seems to crash sidestore. https://user-images.githubusercontent.com/64176728/206938793-05e27884-66e6-4e26-a489-b40036a44400.MOV

Cannot replicate this on my XS running iOS 16.1

**Pull request merged**
