### PR TITLE
[WIP] SwiftUI

### LINKED ISSUE #85: Rewrite all Storyboard UI into SwiftUI
This will aid in more rapid collaboration and development once finished.

### PR DESCRIPTION
**Pull request by JoeMatt**
Clone and rebase of https://github.com/fabianthdev/SideStore

### CODE REVIEW

**Comment by lonkelle** [comment]
This can, in the future, be pulled and be part of the "advanced" settings" to "turn on beta UI" as @fabianthdev mostly has that boolean existing in their branch anyway. But their branch is still based off an older version of SideStore so the conflicts might be annoying.

**Review by lonkelle — CHANGES_REQUESTED** [review]
This can, in the future, be pulled and be part of the "advanced" settings" to "turn on beta UI" as @fabianthdev mostly has that boolean existing in their branch anyway. But their branch is still based off an older version of SideStore so the conflicts might be annoying.

**Comment by JoeMatt** [comment]
> This can, in the future, be pulled and be part of the "advanced" settings" to "turn on beta UI" as @fabianthdev mostly has that boolean existing in their branch anyway. But their branch is still based off an older version of SideStore so the conflicts might be annoying.

That's the preferable idea, but the way this PR was made, it overwrites code in a lot of areas making it difficult to fork the UI at boot time.

Provenance has two UI classes and root views and switches them at boot depending on setting. This would have to be rewritten a bit to function that way.

**Comment by fabianthdev** [comment]
So, after rebasing and updating my branch and also adding new features, I'm now joining this discussion on my PR.
As indicated by the message from the GitHub bot, a new build of this version of SideStore is now available.

To get an overview of the current state of development the following list shows most known issues. This list will be updated here as development progresses.

**Known Issues**
- [ ] Many features are still missing from the app
- [ ] App ratings are shown when no ratings are available
- [ ] App crashes when opening the list of App IDs when not signed in
- [ ] App ID list UI issues
- [ ] Trusted Sources are missing from the list of sources
- [ ] Remaining days until the app has to be refreshed are `floor`ed instead of `ceil`ed
- [ ] Credits links push an SFSafariView instead of presenting it modally
- [ ] "Refresh All" in My Apps does not work

**Comment by Spidy123222** [comment]
Scaling seems a bit off for my iPhone 8 Plus. 

Develop:
EC2D424E-DF6D-49BE-BCC9-8A13B3DBBD15

SwiftUI:
3F0F2D1B-F725-4A4F-85DA-0136BD63E3BA

Also the sources page seems a bit dull in color.

**Comment by fabianthdev** [comment]
I've just added my latest changes with a redesigned and updated app detail page, a lot of fixes and UI improvements, and all new changes from `develop`. The GitHub Actions build should be done in the next few minutes.

**Comment by fabianthdev** [comment]
Another day, another update: The most recent commits contain a lot of UI fixes, including fixes for the full screen app previews and App IDs list.
I've also added all debug options from the UIKit version, including the error log and refresh attempt list. I've also improved the "Reset Pairing File" debug action to automatically quit SideStore after the file has been deleted.

**Comment by fabianthdev** [comment]
My latest commit adds a [LocalConsole](https://github.com/duraidabdul/LocalConsole), to which `STDOUT` and `STDERR` are redirected. This can come in very handy for debugging purposes.

IMG_02939BB46618-1

**Comment by Spidy123222** [comment]
SideStore rewrite is replacing this but we will likely reference it so for now we will close this PR.

**Pull request closed without merging**
