### PR TITLE
Change UI color

### PR DESCRIPTION
**Pull request by LitRitt**
Updates UI color to better match the new icon, and differentiate from "delta purple"

### CODE REVIEW

**Comment by f1shy-dev** [comment]
Can you include some screenshots?

**Comment by LitRitt** [comment]
A424F45B-954E-4C6C-9C5A-615CEBEC29AE
479FD891-DE0F-4BC7-B0D4-53AD87E4798E
61FAEA12-3063-4354-9814-5AA1DEB539CF

**Comment by wyldcrd** [comment]
Can there be color settings so that people can make custom themes instead

**Comment by LitRitt** [comment]
> Can there be color settings so that people can make custom themes instead

There is an ongoing SwiftUI rewrite of the interface. This change is only meant to make the color scheme cohesive with the new app icon. Nothing is final, just cleaning up for soft release

**Comment by lonkelle** [comment]
This is perfect subtle change for the soft release, nice! ❤️‍🔥

**Pull request closed without merging**
