### PR TITLE
Remove SideServer from monorepo

### LINKED ISSUE #24: Move SideServer for macOS into a separate repo
This will make it easier to track against the Windows and Linux versions, as well as make it easier to rewrite AltServer when the time comes.

### PR DESCRIPTION
**Pull request by JJTech0130**
Closes #24

### CODE REVIEW

**Comment by JJTech0130** [comment]
If I brought this up-to-date, would it get merged? It's been sitting here since June without being touched.

**Comment by Spidy123222** [comment]
> If I brought this up-to-date, would it get merged? It's been sitting here since June without being touched.

From what it seems like it needs a review. Could request more developers about it on the GitHub or in the discord to look into it. In my opinion it doesn't seem anything Is wrong.

**Comment by jkcoxson** [comment]
Let's get this one merged, looks like it just needs to be upstreamed

**Comment by JJTech0130** [comment]
Oh, bother. There's a merge conflict in the `.xcodeproj`... the only way to fix that is to just re-edit it with Xcode, right... :(

**Comment by JoeMatt** [comment]
> Oh, bother. There's a merge conflict in the `.xcodeproj`... the only way to fix that is to just re-edit it with Xcode, right... :(

i can do it, it's manual using Diff app, but I've done it a million times, I'm pretty good at it

**Comment by JoeMatt** [comment]
I rebased and pushed this.

I split this into 2 commits,
1. deltes the file
2. modifies the xcodeproj


the xcodeproj diff was confusing in places, tried my best, but please double check i didn't remove needed files by accident. I can't compile at the moment

**Comment by JoeMatt** [comment]
rebased and tested.

Merging now

**Pull request merged**
