### PR TITLE
Replace sideloady with Macley anisette.

### PR DESCRIPTION
**Pull request by Spidy123222**
Thanks to macley in discord for anisette server we can use. This would fix problems with what sideloady causes for signing into enterprise and org accounts and some dev accounts.

### CODE REVIEW

**Comment by jkcoxson** [comment]
This is replacing one band-aid with another, this should be user definable

**Comment by Spidy123222** [comment]
> This is replacing one band-aid with another, this should be user definable

Yeah that’s correct but it would help out for the moment for current devs and users while we figure out a userdefineable method. Also this needs testing.

**Comment by jawshoeadan** [comment]
This has yet to be tested, and for the moment it is less than or just as reliable as the current method. We already are planning to make this user definable. We should only be creating PRs for changes that we're sure need to be implemented.

**Comment by Spidy123222** [comment]
> This has yet to be tested, and for the moment it is less than or just as reliable as the current method. We already are planning to make this user definable. We should only be creating PRs for changes that we're sure need to be implemented.

Their server uses provision like we suggested to use as they wanted to help us with doing a anisette server. This was meant to help our devs with the org and enterprise logins and some of the users/devs problems with -38604. Yes it’s a bandaid replacement but atleast we would be able to get more testing with it IF it works.

**Comment by jawshoeadan** [comment]
A pull request is meant to bring code into the main branch. Until we have the finalized version that we want to bring to the project, we'll test in different branches and forks before bringing it to the main project.

**Comment by JJTech0130** [comment]
I think that we should test if it fixes the enterprise thing before closing it

**Comment by JJTech0130** [comment]
I agree that it’s a temporary solution that shouldn’t be in the final release, but for now, enterprise account development is blocked and this seems like an appropriate stop-gap so development can continue.
We can make a fancy picker menu later

**Comment by Spidy123222** [comment]
It has been tested in the dev discord that it helps with such issue with logging in for both org/enterprise and users that get 38604 error during login.

**Comment by jawshoeadan** [comment]
Because adding a user defined setting will take longer, and this is confirmed to fix it, I'm much more comfortable with merging if everyone agrees

**Comment by jkcoxson** [comment]
I still don't like this PR, but it seems I'm in the minority here so to keep the peace I'll keep out.

**Review by JoeMatt — APPROVED** [review]

**Comment by JoeMatt** [comment]
> This is replacing one band-aid with another, this should be user definable

We just need code to change `UserDefaults.standard.string(forKey: "customAnisetteURL")`

**Comment by JoeMatt** [comment]
@Spidy123222 can you rebase this to remove the merge from develop.
Keeps more readable history that way.


Just rebase then force push, reviews will have to be redone.

**Review by JoeMatt — CHANGES_REQUESTED** [review]
Rebase history

**Comment by Spidy123222** [comment]
> @Spidy123222 can you rebase this to remove the merge from develop.
> 
> Keeps more readable history that way.
> 
> 
> 
> 
> 
> Just rebase then force push, reviews will have to be redone.

Will do when i get time but aren't we just going to rebase anyways?

**Comment by JoeMatt** [comment]
PRs with multi commits I prefer to use a merge commit for easier unrolling if issues

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Spidy123222** [comment]
> > This is replacing one band-aid with another, this should be user definable
> 
> We just need code to change `UserDefaults.standard.string(forKey: "customAnisetteURL")`

Doesn’t https://github.com/SideStore/SideStore/pull/120 fix that issue?

**Comment by JoeMatt** [comment]
> > > This is replacing one band-aid with another, this should be user definable
> 
> > 
> 
> > We just need code to change `UserDefaults.standard.string(forKey: "customAnisetteURL")`
> 
> 
> 
> Doesn’t https://github.com/SideStore/SideStore/pull/120 fix that issue?

Not really. 

Info plist isn't user editable unless modified before build or resigned and reinstall.

There's no way yet to change it in an active app.

That PR just stores it in userdefualts but functionally has no different effect than reading from plist without UI or Settings.bundle to edit the user value.

Hard coding a backup really is kind of pointless. 

The default should be in the plist and the user entered one through an input field should be the user defaults value. 

Then the getter should read Udefaults, if nil, the info.plist which should never be empty anyway.

**Comment by Spidy123222** [comment]
> > > > This is replacing one band-aid with another, this should be user definable
> > 
> > > 
> > 
> > > We just need code to change `UserDefaults.standard.string(forKey: "customAnisetteURL")`
> > 
> > 
> > 
> > Doesn’t https://github.com/SideStore/SideStore/pull/120 fix that issue?
> 
> Not really. 
> 
> Info plist isn't user editable unless modified before build or resigned and reinstall.
> 
> There's no way yet to change it in an active app.
> 
> That PR just stores it in userdefualts but functionally has no different effect than reading from plist without UI or Settings.bundle to edit the user value.
> 
> Hard coding a backup really is kind of pointless. 
> 
> The default should be in the plist and the user entered one through an input field should be the user defaults value. 
> 
> Then the getter should read Udefaults, if nil, the info.plist which should never be empty anyway.

I see well I don't think I have the skills to do a ui without a mac (trial and error using GitHub Actions) to create it. Someone else would have to do the customizable ui but I don't think this is the appropriate pr to do it as this only changes the default anisette server and not meant to be user swappable at the time being. Someone could do a pr or modify this one and make it be a different pr altogether to fix that.

I mean if your wanting we can change the default to be jkcoxsons altserver-Linux link as recent reports suggest that it could work better with sideloading than a provision version (like macley anisette) for the time being. Would like to see your input on this.

**Comment by JoeMatt** [comment]
closing in favour of #127

**Pull request closed without merging**
