### PR TITLE
Anisette URL - Pullrequests/jkcoxson/develop

### PR DESCRIPTION
**Pull request by JoeMatt**
Rebase and edit of #120 

- User defaults extension used rather than strings
- Info.plist key different than Settings.bundle/UserDefaults custom key
- Anisette manager class for convenience

### CODE REVIEW

**Comment by upal212** [comment]
Default anisette URL did not have to be removed as the change issue was already fixed by jkcoxson.
Now it shows completely blank with the new build due to the null value.

**Comment by JoeMatt** [comment]
> Default anisette URL did not have to be removed as the change issue was already fixed by jkcoxson.
> Now it shows completely blank with the new build due to the null value.

Read the code again. The blank value is for userAnisette. Default Anisette is from the Info.plist.

Info.plist should be immutable.

I did just spot a bug though, I don't check for empty string. I thought the URL(string) != nil would be enough but not sure if "" creates a valid URL. I'll just check for empty though.

**Comment by Spidy123222** [comment]
Seems like selecting mobiledevicepairing file in runtime isn't working for everyone as it get greyed our when the files pop up comes during setup for some people. It has worked for me likely because I had jitterbug app on device but could be wrong on why.

**Comment by JoeMatt** [comment]
> Seems like selecting mobiledevicepairing file in runtime isn't working for everyone as it get greyed our when the files pop up comes during setup for some people. It has worked for me likely because I had jitterbug app on device but could be wrong on why.

which file extensions. We have to add them. I think it only takes .plist, i had to rename mine.

**Comment by Spidy123222** [comment]
It's currently (.mobiledevicepairing) which is what jitterbug produces and likely some other programs.

**Comment by upal212** [comment]
Changing of Anisette server settings bundle seems to be broken, as the app signs without any server address added and changing the address does not make a change in app.

**Comment by JoeMatt** [comment]
> Changing of Anisette server settings bundle seems to be broken, as the app signs without any server address added and changing the address does not make a change in app.

That's not how settings works. It doesn't need to be set at build time.
The Info.plist does, the Settings value should be blank until a user sets it.

**Comment by upal212** [comment]
> > Changing of Anisette server settings bundle seems to be broken, as the app signs without any server address added and changing the address does not make a change in app.
> 
> That's not how settings works. It doesn't need to be set at build time. The Info.plist does, the Settings value should be blank until a user sets it.

I am aware of that but the value of it does not change after changing it under settings.
For example even if you specificy a different host or an invalid one, the app is still signing the apps fine. My guess is that it is defaulting the anisette values to its default despite of making changes to it.

**Comment by JoeMatt** [comment]
> > > Changing of Anisette server settings bundle seems to be broken, as the app signs without any server address added and changing the address does not make a change in app.
> 
> > 
> 
> > That's not how settings works. It doesn't need to be set at build time. The Info.plist does, the Settings value should be blank until a user sets it.
> 
> 
> 
> I am aware of that but the value of it does not change after changing it under settings.
> 
> For example even if you specificy a different host or an invalid one, the app is still signing the apps fine. My guess is that it is defaulting the anisette values to its default values despite of making any changes to it.

The active url should be logged to console at activation time. 

What's it printing?

**Comment by upal212** [comment]
> > > > Changing of Anisette server settings bundle seems to be broken, as the app signs without any server address added and changing the address does not make a change in app.
> > 
> > 
> > > 
> > 
> > 
> > > That's not how settings works. It doesn't need to be set at build time. The Info.plist does, the Settings value should be blank until a user sets it.
> > 
> > 
> > I am aware of that but the value of it does not change after changing it under settings.
> > For example even if you specificy a different host or an invalid one, the app is still signing the apps fine. My guess is that it is defaulting the anisette values to its default values despite of making any changes to it.
> 
> The active url should be logged to console at activation time.
> 
> What's it printing?

Yes the URL was set during the time of activation and let’s say I make any change to the host or URL. It does not seem to be creating any logs under the server neither is the app asking for a re-login which should be it’s normal nature due to the anisette change.

**Comment by upal212** [comment]
> > > > Changing of Anisette server settings bundle seems to be broken, as the app signs without any server address added and changing the address does not make a change in app.
> > 
> > 
> > > 
> > 
> > 
> > > That's not how settings works. It doesn't need to be set at build time. The Info.plist does, the Settings value should be blank until a user sets it.
> > 
> > 
> > I am aware of that but the value of it does not change after changing it under settings.
> > For example even if you specificy a different host or an invalid one, the app is still signing the apps fine. My guess is that it is defaulting the anisette values to its default values despite of making any changes to it.
> 
> The active url should be logged to console at activation time.
> 
> What's it printing?

Yes the URL was set during the time of activation as it was set to blank as default and let’s say I make any change to the host or URL. It does not seem to be creating any logs under the server neither is the app asking for a re-login which should be it’s normal nature due to the anisette change.

Could you tell me how is it signing the app without any anisette url set to it and even after putting an invalid url it seems to be working. Does it fetch any default anisette from before?

Edit: Note that the changes used to work before. As per the tests it seems to be always fetching the values from FetchAnisetteDataOperation.swift despite of changing it as the ‘ customAnisetteURL ‘ is set to sideloadly.

**Comment by jkcoxson** [comment]
I can confirm that setting the setting in the settings app does nothing.

**Comment by Spidy123222** [comment]
I also can confirm it doesn't work. Seems it just ignores it.

**Comment by JoeMatt** [comment]
OK, so it seems the URL change works, as in, the code that reads the plists/settings is working, but there's another step i didn't know about, which is we have to detect that change on app open and login?

Can you tell me what exactly has to be done.

I'll store another key/value for what the signed in URL is, and if the selected URL is different, re-register whatever it is that's required. You gotta tell me though, I have no clue what the workflow is, I just wrote the code to read the URL from settings.

**Comment by upal212** [comment]
Can confirm the changes is working now.

**Comment by JoeMatt** [comment]
k sounds good then.

**Pull request merged**
