### PR TITLE
Remove AppCenter Analytics

### PR DESCRIPTION
**Pull request by jawshoeadan**

### CODE REVIEW

**Comment by Spidy123222** [comment]
Is there a reason we are removing analytics when we should have our own?

**Comment by jkcoxson** [comment]
It’s a community app. We have no business capturing data from the community.

**Comment by JoeMatt** [comment]
We don't want crash logs?

**Comment by jawshoeadan** [comment]
We can have people send them in, but I don’t think we should have them by default. Also it’s another thing we’d have to maintain/pay for.

**Comment by jawshoeadan** [comment]
Also, don’t merge until I fix CI

**Comment by JoeMatt** [comment]
> We can have people send them in, but I don’t think we should have them by default. Also it’s another thing we’d have to maintain/pay for.

Isn't it free and opt-in?

I use it on Provenance and never had an issue or fee. 

You can set it to opt in also.

**Comment by jawshoeadan** [comment]
> > We can have people send them in, but I don’t think we should have them by default. Also it’s another thing we’d have to maintain/pay for.
> 
> Isn't it free and opt-in?
> 
> I use it on Provenance and never had an issue or fee.
> 
> You can set it to opt in also.

Yeah, we’re discussing in the Discord that we wouldn’t use AppCenter if we are doing analytics, so we’d still use this PR.

**Comment by jawshoeadan** [comment]
Still up for discussion whether this should be done, closing for now

**Pull request closed without merging**
