### PR TITLE
beta

### PR DESCRIPTION
**Pull request by stossy11**
### Changes

- Fix bug
- Change UI for QOL

### Todo before merge

- [x] Finish UI changes
- [ ] Test

Closes #1234

### CODE REVIEW

**Comment by stossy11** [comment]
TF DID I DO

**Comment by stossy11** [comment]
DIDNT MEAN

**Comment by stossy11** [comment]
IGNORE THIS

**Review by SternXD — COMMENTED** [review]
Holy pings

**Pull request closed without merging**
