### PR TITLE
Rebase 2.0 wip

### PR DESCRIPTION
**Pull request by nythepegasus**
### Changes

- AltStore 2.0 merges
### Todo before merge
- [ ] Test
- [ ] Ensure no regressions

### CODE REVIEW

**Comment by nythepegasus** [comment]
@mahee96 Recreated your branch without the merge conflicts

**Comment by mahee96** [comment]
@nythepegasus , we aren’t merging this yet into develop branch, this is what i have so far and I am putting it out for others.

this can stay in the separate branch rebase-2.0-wip until we iron out the issues and prepare “develop” branch for final merge

**Comment by nythepegasus** [comment]
Ofc! I'm not sure how much I broke, but this is definitely a great starting point for further merging.

**Comment by mahee96** [comment]
Just force merge it for now, we can fix it a bit by bit or just use this branch as reference if there are other plans.

i couldn’t push it directly myself so had to create a PR

**Comment by nythepegasus** [comment]
I'm not going to push this to develop yet, I just wanted to fix the merge conflicts I saw with your PR.

**Comment by mahee96** [comment]
I am away from keyboard and typing from mobile browser, can you switch the target branch for PR to the “rebase-2.0-wip” branch that i had created yesterday in sidestore?

**Comment by nythepegasus** [comment]
@mahee96 Yes, you should have permission to push to this branch directly now though, and we'll be merging it into develop once it's ready!

**Comment by mahee96** [comment]
@nythepegasus can you switch it to “rebase-2.0-wip”. i still the target to be develop

**Comment by polymo1** [comment]
Screenshot_20241210_074915_Firefox

**Comment by mahee96** [comment]
@polymo1, probably need to create a new PR with proper target branch :(

**Comment by mahee96** [comment]
Closing this, will create new PR with proper target branch

**Comment by junepark678** [comment]
Are we anywhere close to merging?

**Comment by mahee96** [comment]
yeah, I am just working on the altbackup issue, I will prepare this for merging if I can't resolve it soon enough

**Review by silver638 — COMMENTED** [review]
7cf8095545830fc4c38d2c17e5faeb9e02eddf96

**Review by Void260 — COMMENTED** [review]
Better

**Pull request merged**
