### PR TITLE
[WIP] Auto fetch bundleid

### PR DESCRIPTION
**Pull request by Spidy123222**
This is a draft pull request to remove some hardcoded bundleid code to make it easier to change bundleid’s. I encourage others to tag along as this as quite a bit of bundleid stuff hardcoded in. Currently it does not build as it has some compilation errors but has worked for doing some separately.

### CODE REVIEW

**Comment by ktprograms** [comment]
If you're not getting it from the bundle once in some global constants file, wouldn't it be better to just put the bundle code directly without a variable?

**Comment by Spidy123222** [comment]
> If you're not getting it from the bundle once in some global constants file, wouldn't it be better to just put the bundle code directly without a variable?

Latest commit should solve your question/answer. I made it use a global variable in a preexisting global constants file and now acts the same.

**Comment by Spidy123222** [comment]
I can now confirm that this builds and works on my idevice. testing would be appreciated.

**Comment by Spidy123222** [comment]
This is all i can get to that i am not fearful of touching incase if things break

**Comment by Spidy123222** [comment]
i just found that the official source broke via this

**Comment by Spidy123222** [comment]
Latest commits didn't seem to fix it. Is this a actions issue?

**Comment by Spidy123222** [comment]
So currently it seems to build fine. But however seems like the default Sidestore source doesn’t seem to act right as it doesn’t have the update prompt and is seen in the browse tab again.

**Comment by JoeMatt** [comment]
I resolved the conflict, please double check my work.

We still using alpha/beta/release?

**Comment by Spidy123222** [comment]
> I resolved the conflict, please double check my work.
> 
> 
> 
> We still using alpha/beta/release?

It's release but seems like it has some issues and I don't know how to fix. I accidentally made it not a draft at one point.

**Comment by Spidy123222** [comment]
I just realized I might of added commits to this pr from commits from #120.

**Comment by JoeMatt** [comment]
Marking this as a draft PR. 

Feel free to change when this is ready.

**Comment by Spidy123222** [comment]
> Marking this as a draft PR.
> 
> Feel free to change when this is ready.

Yeah thanks I couldn’t find how to change it back from accidentally doing normal pr.

**Comment by lonkelle** [comment]
@Spidy123222 What on this PR needs to be done? I thought this was already committed tbh.

**Comment by Spidy123222** [comment]
> @Spidy123222 What on this PR needs to be done? I thought this was already committed tbh.

There is some quite nasty bugs with it where it breaks browse section and the default source doesn't bind no more which crashes sources menu also. I think might of did some things incorrect. This is also not upstreamed so some of this could of been fixed.

**Comment by lonkelle** [comment]
@Spidy123222 Gotcha, so this is future code to allow us to change bundle id's of apps at will? Or does this focus only on SideStore's bundle ID?

**Comment by Spidy123222** [comment]
It focuses us able to change bundleid of the app entirely at will. I'm not sure how I could bind it to something like the xcconfig but you just change the bundleid in the shared file.

**Comment by JoeMatt** [comment]
TODO
- [ ] resolve conflicts
- [ ] squash multiple commits

**Comment by JoeMatt** [comment]
close for #203

**Pull request closed without merging**
