### PR TITLE
Add cargo build to build script

### PR DESCRIPTION
**Pull request by jawshoeadan**
This should be all that we need to build with secret tunnel, but I won't be able to test until @jkcoxson's pr is merged

### CODE REVIEW

**Comment by JJTech0130** [comment]
Rustup isn’t already installed?

**Comment by JJTech0130** [comment]
Yeah the runner comes with Rustup 1.25.1

**Comment by jawshoeadan** [comment]
You're right whoops

**Comment by Spidy123222** [comment]
I already did a pr for adding rust and improving building in jkcoxsons PR. My PR is on their fork.

**Comment by jawshoeadan** [comment]
Sorry didn't see you already did it.

**Pull request closed without merging**
