### PR TITLE
SemVer comparison

### PR DESCRIPTION
**Pull request by naturecodevoid**
This PR adds SemVer comparison when comparing 2 versions to see if there is an update available.

Side note: according to SemVer, `0.3.0` > `0.3.0-nightly.1`, so we should probably increase the version.

### CODE REVIEW

**Comment by naturecodevoid** [comment]
Builds are failing because of minimuxer. We need to point the submodule to SideStore/mini user and fix the Cargo.toml file

**Review by Nythepegasus — COMMENTED** [review]
Everything looks good! I think you should revert the .gitignore (just to keep the PR on topic) but other than that it seems ready to push!

**Comment by naturecodevoid** [comment]
I added the part to the gitignore because I had a lot of those ._ prefixed files and it was much easier just to gitignore them. Not sure why it changed the end of the file though

**Comment by hiraginoyuki** [comment]
I think you should do that in [`$XDG_CONFIG_HOME/git/ignore`](https://git-scm.com/docs/gitignore/2.33.0).

**Comment by naturecodevoid** [comment]
Thanks!

**Comment by naturecodevoid** [comment]
oh no. Complete misclick, did not mean to merge.

**Pull request merged**
