### PR TITLE
Merge upstream 9/13/2022

### PR DESCRIPTION
**Pull request by Spidy123222**

### CODE REVIEW

**Comment by JJTech0130** [comment]
Wow, this is a lot of commits really quick lol. Seems he's started working on it again.

**Comment by Spidy123222** [comment]
> Wow, this is a lot of commits really quick lol. Seems he's started working on it again.

Seems like a bunch of stuff for the new widget system ios 16 has and some bug fixes for AltStore.

**Comment by jkcoxson** [comment]
If we want to do this, we should upstream with a much more recent commit, but I don't think it's necessary.

**Comment by Spidy123222** [comment]
> If we want to do this, we should upstream with a much more recent commit, but I don't think it's necessary.

This pr seems to be updating with anything they do It has latest commits. I can rename pr if we want to upstream at some point.

**Pull request closed without merging**
