### PR TITLE
Bump version to 0.1.1

### PR DESCRIPTION
**Pull request by Spidy123222**
This changes version to 0.1.1. This would allow us to do an ota update also

### CODE REVIEW

**Review by upal212 — CHANGES_REQUESTED** [review]
"versionDescription": "If you see this error then please sideload the new version of SideStore via AltServer!"
Edit: I would also prefer to not force update the users until version 1.0.0/stable build is out.

**Comment by Spidy123222** [comment]
> "versionDescription": "If you see this error then please sideload the new version of SideStore via AltServer!"

Can you please specify the issue. The app no longer uses this file to update. Only old versions did so makes sense to have said message. The merge will need to also have an actual update happen to update to latest. Our updates happen n the apps.json repo and yes Ik weird repo name.

**Comment by upal212** [comment]
> > "versionDescription": "If you see this error then please sideload the new version of SideStore via AltServer!"
> 
> Can you please specify the issue. The app no longer uses this file to update. Only old versions did so makes sense to have said message. The merge will need to also have an actual update happen to update to latest. Our updates happen n the apps.json repo and yes Ik weird repo name. I do need to change wording tho.

Just did a spell check on the alert. And formatted it nicely.

**Comment by Spidy123222** [comment]
> > > "versionDescription": "If you see this error then please sideload the new version of SideStore via AltServer!"
> > 
> > 
> > Can you please specify the issue. The app no longer uses this file to update. Only old versions did so makes sense to have said message. The merge will need to also have an actual update happen to update to latest. Our updates happen n the apps.json repo and yes Ik weird repo name. I do need to change wording tho.
> 
> Just did a spell check on the alert. And formatted it nicely. Edit: Making it more use friendly to the end users.

Hope that satisfies your review. Also it’s not an error but a notification to update because they are in too old of version.

**Comment by upal212** [comment]
> > > > "versionDescription": "If you see this error then please sideload the new version of SideStore via AltServer!"
> > > 
> > > 
> > > Can you please specify the issue. The app no longer uses this file to update. Only old versions did so makes sense to have said message. The merge will need to also have an actual update happen to update to latest. Our updates happen n the apps.json repo and yes Ik weird repo name. I do need to change wording tho.
> > 
> > 
> > Just did a spell check on the alert. And formatted it nicely. Edit: Making it more use friendly to the end users.
> 
> Hope that satisfies your review. Also it’s not an error but a notification to update because they are in too old of version.

Yup that should look much neater than before, just wanted the spellchecked and formatted of the wordings.
Hence, I edited the error out, as it was always a notification.

**Review by JoeMatt — CHANGES_REQUESTED** [review]
MARKETING_VERSION is set in the .xcconfig.

The `[pbxproj](https://github.com/SideStore/SideStore/pull/141#diff-26ab9d1870e5f7e408fb64d3dc3d8751bea292c3975da2c76ce6733ea0538463)` should just have $(MARKETING_VERSION)

**Comment by JoeMatt** [comment]
I fixed and rebased this.

Changing `MARKETING_VERSION` in the `xcconfig` is all that's required to update the app info now.

**Review by JoeMatt — APPROVED** [review]

**Review by JoeMatt — APPROVED** [review]

**Pull request merged**
