### PR TITLE
[WIP] Use compile time script to generate org ids

### PR DESCRIPTION
**Pull request by JoeMatt**
- add rename scripts
- add rename to project
- use constants in sources
- replace libfragmentzip static iOS library for cross compatible iOS/macOS sub-[module](https://github.com/SideStore/libfragmentzip) 
- compile-time support email, server IP and URL

Uses a script to generate a swift and .h file with static strings that are generated from XCode environment variables.

That library 'Constants' can then be imported into other targets and compile time vars can be used in compiled code with `import Constants` and `Constats.k....` strings

### CODE REVIEW

**Comment by JoeMatt** [comment]
this might work, but i think the created files hang and xcode doesn't update them even though they are set for input and output files in the script phase.

let me know if this works for you.

**Comment by jkcoxson** [comment]
How come actions are failing?

**Comment by JJTech0130** [comment]
Seems like he added a sub module, but the commit he added doesn’t exist?

**Comment by JoeMatt** [comment]
closing, not really needed anymore

**Comment by lonkelle** [comment]
Since somehow I ended up at this ticket from my email even tho it's been long closed. I wanted to add to what @JJTech0130 was saying. 

Because sometimes I've seen this whole "the commit not existing" thing. So to anyone who makes it to this ticket with the same kind of submodule GitHub commit doesn't exist error. This has solved it for me in the past, adding the remote flag. 

`git submodule update --force --recursive --init --remote`

Because the commit actually does exist. Remote does something. Idk. JITs weird, seems like bad UX that I had to add remote when it could have just checked for me instead of erroring out. 

Engineers just don't think of UX. What am I even talking about rn. I'm outta here. ✌️

**Pull request closed without merging**
