### PR TITLE
Add Vanity Links

### LINKED ISSUE #433: [FEATURE REQUEST] Add a prerequisite to creating an issue regarding updates.
### Describe the feature

Before creating a Github Issue, the user would be told to ensure that they are on the latest version of SideStore.

### Use cases

Many users recently have created issues and some of those issues were fixable by updating to the latest version of SideStore.

A great example is: #429 where the user was on an old version of SideStore simply because they wanted MDC functionality. If they had seen this message prior to creating the issue, they would not have had to make the issue.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by DatUub**
### Changes

- Fix Added Discord Vanity Link
- Added Checkbox for latest version.

Closes #433

### CODE REVIEW

**Review by DatUub — COMMENTED** [review]
test

**Comment by naturecodevoid** [comment]
No point in using the vanity link imo, all of the cases the discord.gg is used it isn't visible. The vanity link isn't permanent, better to use a permanent invite

**Review by naturecodevoid — CHANGES_REQUESTED** [review]
No point in using the vanity link imo, all of the cases the discord.gg is used it isn't visible. The vanity link isn't permanent, better to use a permanent invite

**Comment by naturecodevoid** [comment]
Also, while I agree something to ensure the user is on the latest version would be good, we need a more robust solution since people may just click the checkbox. Something along the lines of a button in-app to create a bug report that uses GitHub's API to ensure the app is on the latest version.

**Comment by WesleyBryie** [comment]
> Also, while I agree something to ensure the user is on the latest version would be good, we need a more robust solution since people may just click the checkbox. Something along the lines of a button in-app to create a bug report that uses GitHub's API to ensure the app is on the latest version.

Is there a way to only allow issues to come through on github if something specific is done? or maybe a bot that will delete/auto-close issues that don't have a randomly generated 'key' from SideStore?

**Comment by naturecodevoid** [comment]
We should be able to create an API for creating issues instead of going through GitHub's UI

If it hasn't already been done, it should be extremely easy

This would also be a good thing to do once unstable features / feature flags is merged (but this date is currently unknown)

**Comment by naturecodevoid** [comment]
Though this could have cons such as not being able to use the UI to create issues so we may want to make a bot (looking at how other projects that utilize issues heavy such as rust may be helpful)

**Comment by naturecodevoid** [comment]
Closing this since vanity links don't really matter and we use discord.gg/sidestore-[server id] in most places now.

**Pull request closed without merging**
